### ISSUE TITLE
Create a code of conduct

### ISSUE THREAD

**Issue by c8ivanov** [c8ivanov/uoft-cs-slack#4]
As previously agreed, we need a code of conduct to guide communication style and to refer to for conflict mediation.

Previous conversation: https://gist.github.com/0f62fdd478931b30ba69#file-uoft-cs-slack-coc-md
A suggestion from @aashnisshah: http://static.mlh.io/docs/mlh-code-of-conduct.pdf

A few options:
https://github.com/iOS-Developers-Slack/Code-Of-Conduct (Chat CoC)
https://github.com/python/pycon-code-of-conduct/blob/master/code_of_conduct.md (Conference CoC)

**Comment by c8ivanov** [comment]
I've pull-requested the code of conduct in #7.

**Comment by aashnisshah** [comment]
I've been trying to figure out where in Slack these messages were, only to realise they were in Github -_-

I read through, and they look good so far. I'll try and add one or two and refine one or two over the weekend :)

**Comment by c8ivanov** [comment]
#7 merged.
